`timescale 1ns / 1ps

// ============================================================================
// XADC Adapter
// ============================================================================
// Wraps the Vivado XADC Wizard IP (xadc_wiz_0) and exposes a simple
// 12-bit sample output with a single-cycle valid pulse.
//
// Configuration assumed (set in XADC Wizard IP GUI):
//   - Interface: DRP
//   - Timing Mode: Continuous
//   - Startup Channel: Single Channel
//   - Channel: VAUXP6/VAUXN6 (JXADC pins J3/K3)
//   - Unipolar
//   - DCLK: 100 MHz
//   - Conversion rate: 1000 KSPS (we decimate to 360 Hz downstream)
//
// DRP protocol we implement here:
//   1. XADC fires eoc_out pulse when conversion done
//   2. We assert den_in + daddr_in=0x16 (VAUX6 register address)
//   3. XADC asserts drdy_out when do_out is valid
//   4. Latch upper 12 bits as adc_data, pulse adc_valid
// ============================================================================

module xadc_adapter (
    input logic clk,      // 100 MHz dclk
    input logic rst,
    
    // analog input (to/from Pmod JXADC pins J3/K3)
    input logic vauxp6,
    input logic vauxn6,
    
    // decimated output to system_top_wrapper
    output logic [11:0] adc_data,
    output logic adc_valid,
    
    // decimation rate - output every N samples
    // at 961 KSPS actual conversion rate, divide by 2670 for ~360 Hz
    // at 1 MSPS nominal, divide by 2778 for 360 Hz
    input logic [15:0] decimation_count  // e.g. 16'd2670
);

    // ============ XADC IP Signals ============
    logic [6:0] daddr_in;
    logic den_in;
    logic [15:0] di_in;
    logic dwe_in;
    logic [15:0] do_out;
    logic drdy_out;
    logic eoc_out;
    logic eos_out;
    logic busy_out;
    logic [4:0] channel_out;
    logic alarm_out;
    
    // ============ XADC Instantiation ============
    // this is the IP generated by xilinx xadc wizard
    // make sure it's named xadc_wiz_0 when you generate the IP
    xadc_wiz_0 xadc_inst (
        .daddr_in(daddr_in),
        .den_in(den_in),
        .di_in(di_in),
        .dwe_in(dwe_in),
        .do_out(do_out),
        .drdy_out(drdy_out),
        .dclk_in(clk),
        .reset_in(rst),
        .vauxp6(vauxp6),
        .vauxn6(vauxn6),
        .busy_out(busy_out),
        .channel_out(channel_out),
        .eoc_out(eoc_out),
        .eos_out(eos_out),
        .alarm_out(alarm_out),
        .vp_in(1'b0),
        .vn_in(1'b0)
    );
    
    // ============ DRP Read State Machine ============
    // tied off - we only read, never write
    assign di_in = 16'h0000;
    assign dwe_in = 1'b0;
    
    // VAUX6 address = 0x16 (channel 6 data register)
    localparam [6:0] DRP_ADDR_VAUX6 = 7'h16;
    
    typedef enum logic [1:0] {
        IDLE,
        WAIT_EOC,
        READ_DRP,
        WAIT_DRDY
    } state_t;
    
    state_t state;
    logic [15:0] sample_raw;
    logic sample_ready;
    
    always_ff @(posedge clk or posedge rst) begin
        if (rst) begin
            state <= WAIT_EOC;
            den_in <= 1'b0;
            daddr_in <= 7'h0;
            sample_raw <= 16'h0;
            sample_ready <= 1'b0;
        end else begin
            sample_ready <= 1'b0;  // default: pulse only
            
            case (state)
                WAIT_EOC: begin
                    // wait for xadc to finish a conversion
                    den_in <= 1'b0;
                    if (eoc_out) begin
                        // conversion done - initiate drp read
                        daddr_in <= DRP_ADDR_VAUX6;
                        den_in <= 1'b1;
                        state <= WAIT_DRDY;
                    end
                end
                
                WAIT_DRDY: begin
                    // deassert den after one cycle
                    den_in <= 1'b0;
                    if (drdy_out) begin
                        // data is valid on do_out
                        sample_raw <= do_out;
                        sample_ready <= 1'b1;
                        state <= WAIT_EOC;
                    end
                end
                
                default: state <= WAIT_EOC;
            endcase
        end
    end
    
    // ============ Decimation from ~1 MSPS down to 360 Hz ============
    // xadc actual conversion rate ~961 KSPS
    // we drop samples to get closer to 360 hz for ecg
    logic [15:0] dec_counter;
    
    always_ff @(posedge clk or posedge rst) begin
        if (rst) begin
            dec_counter <= 16'h0;
            adc_valid <= 1'b0;
            adc_data <= 12'h0;
        end else begin
            adc_valid <= 1'b0;
            
            if (sample_ready) begin
                if (dec_counter >= decimation_count) begin
                    // output this sample
                    dec_counter <= 16'h0;
                    // xadc gives 16-bit result with valid data in [15:4]
                    // take upper 12 bits for 12-bit resolution
                    adc_data <= sample_raw[15:4];
                    adc_valid <= 1'b1;
                end else begin
                    dec_counter <= dec_counter + 1;
                end
            end
        end
    end

endmodule